-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 20:11:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projroot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projroot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projroot` DEFAULT CHARACTER SET utf8 ;
USE `projroot` ;

-- -----------------------------------------------------
-- Table `projroot`.`pri_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projroot`.`pri_info` (
  `userID` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `gender` VARCHAR(45) NULL,
  `servicetype` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projroot`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projroot`.`student` (
  `profileimage` VARCHAR(45) NOT NULL,
  `subject` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `pri_info_userID` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_student_pri_info`
    FOREIGN KEY (`pri_info_userID`)
    REFERENCES `projroot`.`pri_info` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projroot`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projroot`.`tutor` (
  `caseID` INT NOT NULL,
  `subject` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`caseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projroot`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projroot`.`request` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
